version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__TstComprasConnection=Host=10.197.42.64;Port=5432;Database=TstCompras;Username=postgres;Password=asd
